#  A github workflow to build custom android common kernels with specified parameters
#  Copyright (C) 2025 chickendrop89
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

name: Build Android Common Kernel

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      ack_branch:
        description: 'Android-common-kernel branch'
        required: true
        default: 'common-android13-5.15'
        type: string

      custom_kernel_repo:
        description: 'Custom kernel repository'
        required: true
        default: 'https://github.com/dxcvvxd/device_xiaomi_gemstones-kernel'
        type: string

      custom_kernel_repo_branch:
        description: 'Custom kernel repository branch'
        required: true
        default: 'android13-5.15-lts'
        type: string

      use_latest_clang:
        description: 'Use latest clang prebuilts'
        required: true
        default: true
        type: boolean

      anykernel_url_plus_branch:
        description: 'AnyKernel3 URL + optional branch'
        required: true
        default: 'https://github.com/dxcvvxd/AnyKernel3'
        type: string

      kernel_image_type:
        description: 'Kernel image type'
        required: true
        default: 'Image'
        type: string

      extra_args:
        description: 'Extra arguments passed to build.sh'
        required: false
        type: string

      build_configs:
        description: 'Space-separated list of build configs'
        required: true
        default: 'build.config.gki.aarch64.chickernel.ksun.susfs'
        type: string

jobs:
  build:
    runs-on: ubuntu-24.04

    env:
      BUILD_CONFIGS: ${{ github.event.inputs.build_configs }}
      IMAGE_TYPE: ${{ github.event.inputs.kernel_image_type }}

      ACK_BRANCH: ${{ github.event.inputs.ack_branch }}
      COMMON_REPO: ${{ github.event.inputs.custom_kernel_repo }}
      COMMON_REPO_BRANCH: ${{ github.event.inputs.custom_kernel_repo_branch }}
      AK3_GIT_URL_PLUS_BRANCH: ${{ github.event.inputs.anykernel_url_plus_branch }}

      AK3_DIR: ${{ github.workspace }}/kernel-build/anykernel3
      FINAL_DIR: ${{ github.workspace }}/kernel-build/final_images

    steps:
      - name: Validate inputs
        shell: bash
        run: |
          set -e

          AK3_GIT_URL=$(echo "${AK3_GIT_URL_PLUS_BRANCH}" | awk '{print $1}')
          AK3_GIT_BRANCH=$(echo "${AK3_GIT_URL_PLUS_BRANCH}" | awk '{print $2}')

          echo "AK3_GIT_URL=${AK3_GIT_URL}" >> ${GITHUB_ENV}
          echo "AK3_GIT_BRANCH=${AK3_GIT_BRANCH}" >> ${GITHUB_ENV}

          validate_url() {
            if [[ ! "$1" =~ ^https://.+/.+/.+$ ]]; then
              echo "::error::Invalid URL: $1"
              exit 1
            fi
          }

          validate_single_word() {
            if [[ "$1" =~ [[:space:]] ]]; then
              echo "::error::Invalid $2: $1"
              exit 1
            fi
          }

          validate_url "${COMMON_REPO}"
          validate_url "${AK3_GIT_URL}"

          validate_single_word "${ACK_BRANCH}" "ACK branch"
          validate_single_word "${COMMON_REPO_BRANCH}" "Kernel repo branch"
          validate_single_word "${IMAGE_TYPE}" "Image type"

          if [ -n "${AK3_GIT_BRANCH}" ]; then
            validate_single_word "${AK3_GIT_BRANCH}" "AK3 branch"
          fi

      - name: Setup workspace and manifest
        shell: bash
        env:
          USE_LATEST_CLANG: ${{ github.event.inputs.use_latest_clang }}
          CUSTOM_MANIFEST: .repo/local_manifests/custom.xml
        run: |
          set -e

          REPO_SOURCE=$(echo ${COMMON_REPO} | cut -d'/' -f3)
          REPO_OWNER=$(echo ${COMMON_REPO} | cut -d'/' -f4)
          REPO_NAME=$(echo ${COMMON_REPO} | cut -d'/' -f5)

          mkdir kernel-build
          cd kernel-build

          mkdir -p .repo/local_manifests

          cat > ${CUSTOM_MANIFEST} << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <manifest>
            <remote
              name="common-repo"
              fetch="https://${REPO_SOURCE}/${REPO_OWNER}" />

            <remove-project name="kernel/common" />

            <project
              path="common"
              name="${REPO_NAME}"
              remote="common-repo"
              revision="${COMMON_REPO_BRANCH}">

              <linkfile src="." dest=".source_date_epoch_dir" />
            </project>
          EOF

          if [ "${USE_LATEST_CLANG}" = true ]; then
            cat >> ${CUSTOM_MANIFEST} << EOF
              <remove-project name="platform/prebuilts/clang/host/linux-x86" />

              <project
                path="prebuilts/clang/host/linux-x86"
                name="platform/prebuilts/clang/host/linux-x86"
                revision="main"
                clone-depth="1" />
          EOF
          fi

          echo "</manifest>" >> ${CUSTOM_MANIFEST}

      - name: Download utilities
        working-directory: kernel-build
        shell: bash
        run: |
          set -e

          if [ -z "${AK3_GIT_BRANCH}" ]; then
            git clone --depth=1 "${AK3_GIT_URL}" "${AK3_DIR}"
          else
            git clone --depth=1 \
              -b "${AK3_GIT_BRANCH}" \
              "${AK3_GIT_URL}" \
              "${AK3_DIR}"
          fi

          mkdir -p ~/.bin

          curl -L \
            https://storage.googleapis.com/git-repo-downloads/repo \
            > ~/.bin/repo

          chmod a+rx ~/.bin/repo

          echo "${HOME}/.bin" >> ${GITHUB_PATH}

      - name: Cleanup runner
        uses: rokibhasansagar/slimhub_actions@main

      - name: Setup ccache
        shell: bash
        run: |
          set -e

          sudo apt-get update
          sudo apt-get install -y ccache

          mkdir -p ~/.ccache

          echo "CCACHE_DIR=$HOME/.ccache" >> $GITHUB_ENV
          echo "CCACHE_COMPRESS=true" >> $GITHUB_ENV
          echo "CCACHE_MAXSIZE=10G" >> $GITHUB_ENV

          echo "/usr/lib/ccache" >> $GITHUB_PATH

          ccache -z

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ github.ref_name }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Cache repo
        uses: actions/cache@v4
        with:
          path: kernel-build/.repo
          key: ${{ runner.os }}-repo-${{ env.ACK_BRANCH }}


      - name: Init and sync repo
        working-directory: kernel-build
        shell: bash
        run: |
          set -e

          repo init \
            --no-tags \
            --depth=1 \
            --dissociate \
            -u https://android.googlesource.com/kernel/manifest \
            -b ${ACK_BRANCH}

          repo sync \
            --no-tags \
            --clone-bundle \
            --current-branch \
            --optimized-fetch \
            --fetch-submodules \
            -j$(nproc --all)

      - name: Fix KernelSU versioning
        working-directory: kernel-build/common/KernelSU-Next
        run: |
          git fetch --unshallow || true
          git fetch --tags

      - name: Debug build.sh
        working-directory: kernel-build
        run: |
          pwd
      
          ls -l build
          ls -l build/kernel
          ls -l build/build.sh
      
          readlink -f build/build.sh || true
      
          file build/build.sh || true
          file build/kernel/build.sh || true
      
          head -n 5 build/kernel/build.sh || true

      - name: Build kernels
        working-directory: kernel-build/common
        shell: bash
        env:
          EXTRA_ARGS: ${{ github.event.inputs.extra_args }}
          OUT_DIR: ${{ github.workspace }}/kernel-build/out

          CC: "ccache clang"
          USE_CCACHE: 1
          CCACHE_EXEC: /usr/bin/ccache
        run: |
          set -e

          mkdir -p "${FINAL_DIR}"

          i=1

          for config in ${BUILD_CONFIGS}; do
            echo "======================================="
            echo "Building config ${i}: ${config}"
            echo "======================================="

            BUILD_CONFIG=${config} \
            CC="ccache clang" \
            USE_CCACHE=1 \
            CCACHE_EXEC=/usr/bin/ccache \
            
            BUILD_CONFIG="common/${config}" \
            bash ./build/kernel/build.sh ${EXTRA_ARGS}
            
            if [ -f "${OUT_DIR}/dist/${IMAGE_TYPE}" ]; then
              cp \
                "${OUT_DIR}/dist/${IMAGE_TYPE}" \
                "${FINAL_DIR}/${IMAGE_TYPE}-${config}"
            else
              echo "::error::Missing kernel image for ${config}"
              exit 1
            fi

            ((i++))
          done
          
      - name: Package with AnyKernel3
        working-directory: kernel-build
        shell: bash
        run: |
          set -e

          for config in ${BUILD_CONFIGS}; do
            IMAGE_PATH="${FINAL_DIR}/${IMAGE_TYPE}-${config}"

            if [ ! -f "${IMAGE_PATH}" ]; then
              echo "::error::Missing image for ${config}"
              exit 1
            fi

            WORK_DIR="ak3-${config}"

            cp -r "${AK3_DIR}" "${WORK_DIR}"

            cp "${IMAGE_PATH}" "${WORK_DIR}/${IMAGE_TYPE}"

            cd "${WORK_DIR}"

            zip -r9 \
              "${FINAL_DIR}/${config}.zip" \
              . \
              -x ".git/*" \
              "README.md" \
              "*placeholder*"

            cd ..
          done

      - name: Upload kernel packages
        uses: actions/upload-artifact@v4
        with:
          name: kernel-packages
          path: |
            kernel-build/final_images/*.zip
          if-no-files-found: error
          retention-days: 30
